from __future__ import annotations

from app.Schemas.api_configs import APIConfigTemplate

_DEFAULT_CONTEXT_WINDOW_TOKENS = 128_000
_DEEPSEEK_V4_CONTEXT_WINDOW_TOKENS = 1_000_000


API_CONFIG_TEMPLATES: tuple[APIConfigTemplate, ...] = (
  APIConfigTemplate(
    provider="deepseek",
    provider_label="DeepSeek",
    kind="llm",
    name="DeepSeek LLM",
    base_url="https://api.deepseek.com",
    model="deepseek-v4-pro",
    api_key_required=True,
    thinking_enabled=True,
    context_window_tokens=_DEEPSEEK_V4_CONTEXT_WINDOW_TOKENS,
    supports_thinking=True,
  ),
  APIConfigTemplate(
    provider="deepseek",
    provider_label="DeepSeek",
    kind="embedding",
    name="DeepSeek Embedding",
    base_url="https://api.deepseek.com",
    model="deepseek-embedding",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="openai",
    provider_label="OpenAI",
    kind="llm",
    name="OpenAI LLM",
    base_url="https://api.openai.com/v1",
    model="gpt-4.1-mini",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
  ),
  APIConfigTemplate(
    provider="openai",
    provider_label="OpenAI",
    kind="embedding",
    name="OpenAI Embedding",
    base_url="https://api.openai.com/v1",
    model="text-embedding-3-small",
    api_key_required=True,
    dimensions=1536,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="gemini",
    provider_label="Gemini",
    kind="llm",
    name="Gemini LLM",
    base_url="https://generativelanguage.googleapis.com/v1beta/openai",
    model="gemini-2.5-flash",
    api_key_required=True,
    context_window_tokens=1_000_000,
  ),
  APIConfigTemplate(
    provider="gemini",
    provider_label="Gemini",
    kind="embedding",
    name="Gemini Embedding",
    base_url="https://generativelanguage.googleapis.com/v1beta/openai",
    model="gemini-embedding-001",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="grok",
    provider_label="Grok / xAI",
    kind="llm",
    name="Grok LLM",
    base_url="https://api.x.ai/v1",
    model="grok-3-mini",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
  ),
  APIConfigTemplate(
    provider="grok",
    provider_label="Grok / xAI",
    kind="embedding",
    name="Grok Embedding",
    base_url="https://api.x.ai/v1",
    model="grok-embedding",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="siliconflow",
    provider_label="SiliconFlow",
    kind="llm",
    name="SiliconFlow LLM",
    base_url="https://api.siliconflow.cn/v1",
    model="deepseek-ai/DeepSeek-V3",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_thinking=True,
  ),
  APIConfigTemplate(
    provider="siliconflow",
    provider_label="SiliconFlow",
    kind="embedding",
    name="SiliconFlow Embedding",
    base_url="https://api.siliconflow.cn/v1",
    model="BAAI/bge-m3",
    api_key_required=True,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="ollama",
    provider_label="Ollama",
    kind="llm",
    name="Ollama LLM",
    base_url="http://127.0.0.1:11434/v1",
    model="llama3.1",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
  ),
  APIConfigTemplate(
    provider="ollama",
    provider_label="Ollama",
    kind="embedding",
    name="Ollama Embedding",
    base_url="http://127.0.0.1:11434/v1",
    model="nomic-embed-text",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="lm_studio",
    provider_label="LM Studio",
    kind="llm",
    name="LM Studio LLM",
    base_url="http://127.0.0.1:1234/v1",
    model="local-model",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
  ),
  APIConfigTemplate(
    provider="lm_studio",
    provider_label="LM Studio",
    kind="embedding",
    name="LM Studio Embedding",
    base_url="http://127.0.0.1:1234/v1",
    model="text-embedding-local",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
  APIConfigTemplate(
    provider="vllm",
    provider_label="vLLM",
    kind="llm",
    name="vLLM LLM",
    base_url="http://127.0.0.1:8001/v1",
    model="local-model",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
  ),
  APIConfigTemplate(
    provider="vllm",
    provider_label="vLLM",
    kind="embedding",
    name="vLLM Embedding",
    base_url="http://127.0.0.1:8001/v1",
    model="text-embedding-local",
    api_key_required=False,
    context_window_tokens=_DEFAULT_CONTEXT_WINDOW_TOKENS,
    supports_embeddings=True,
  ),
)
